
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weeding-page
    ports:
      - '5011:3000'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.0.102
      - DB_PORT=5006
      - DB_DATABASE=weendingwong
      - DB_USERNAME=superuser
      - DB_PASSWORD=SE0ptCs58Zap